#
# Module manifest for module 'Terraform'
#
# Generated by: Paul Kelly
#
# Generated on: 4/14/2020
#

@{

# Version number of this module.
ModuleVersion = '1.0.3'

# ID used to uniquely identify this module
GUID = '3ab44793-8483-4b09-99d7-9558089c832e'

# Author of this module
Author = 'Paul Kelly'

# Copyright statement for this module
Copyright = '(c) 2020 Paul Kelly. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell module for the Terraform Cloud/Enterprise API'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '3.0'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @('Private.ps1')

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @('Terraform.Format.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('Public')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Terraform','Enterprise','TFE','Cloud','API','Module','Registry')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/pkelly808/Terraform/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/pkelly808/Terraform'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
